services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    NovemberFive\AwsBundle\Service\AWSManager:
        arguments:
            - ~
            - ~
            - ~
            - ~
        public: false
    NovemberFive\AwsBundle\Service\AWSManagerInterface: '@NovemberFive\AwsBundle\Service\AWSManager'

    NovemberFive\AwsBundle\Service\SQSManager:
        calls:
            - [ setClient, [ 'Aws\Sqs\SqsClient', '%november_five_aws.sqs_version%' ] ]

    NovemberFive\AwsBundle\Service\KMSManager:
        arguments:
            $kmsKey: ~
        calls:
            - [ setClient, [ 'Aws\Kms\KmsClient', '%november_five_aws.kms_version%' ] ]

    NovemberFive\AwsBundle\Service\SNSManager:
        calls:
            - [ setClient, [ 'Aws\Sns\SnsClient', '%november_five_aws.sns_version%' ] ]
            - [ setLogger, [ '@?monolog.logger' ] ]

    NovemberFive\AwsBundle\Service\S3Manager:
        calls:
            - [ setClient, [ 'Aws\S3\S3Client', '%november_five_aws.s3_version%' ] ]

    NovemberFive\AwsBundle\Service\DynamoDBManager:
        calls:
            - [ setClient, [ 'Aws\DynamoDb\DynamoDbClient', '%november_five_aws.dynamodb_version%' ] ]

    NovemberFive\AwsBundle\Service\LambdaManager:
        calls:
            - [ setClient, [ 'Aws\Lambda\LambdaClient', '%november_five_aws.lambda_version%' ] ]